version = 1

test_patterns = [
	"*/test/**",
	"*/test/**/*.py"
]

exclude_patterns = [
    "twisted/plugins/**",
    "examples/**",
	  "*/test/**",
	  "*/test/**/*.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
