language: python
sudo: false

install:
  - pip install tox codecov

env:
  - TOX_ENV=flake8
  - TOX_ENV=pypy-twtrunk
  - TOX_ENV=pypy-trollius
  - TOX_ENV=py27-twtrunk
  - TOX_ENV=py27-trollius
  - TOX_ENV=py33-twtrunk
  - TOX_ENV=py33-trollius
  - TOX_ENV=py34-twtrunk
  - TOX_ENV=py34-asyncio
  - TOX_ENV=pypy-tw122
  - TOX_ENV=pypy-tw132
  - TOX_ENV=pypy-twcurrent
  - TOX_ENV=py26-tw122
  - TOX_ENV=py26-tw132
  - TOX_ENV=py26-twcurrent
  - TOX_ENV=py27-tw122
  - TOX_ENV=py27-tw132
  - TOX_ENV=py27-twcurrent

script:
  - tox -c tox.ini -e $TOX_ENV

after_script:
  - codecov

notifications:
   irc:
      channels:
         - "irc.freenode.org#autobahn"
      use_notice: true
      skip_join: true
